spring:
  application:
    name: kafka-order-system

  datasource:
    url: jdbc:postgresql://localhost:5432/orders_db?options=-c%20TimeZone%3DUTC
    username: orders_user
    password: orders_password

  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        format_sql: true

  data:
    redis:
      host: localhost
      port: 6379

  kafka:
    bootstrap-servers: localhost:9092

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: false
        enable.idempotence: true
        acks: all
        compression.type: lz4
        linger.ms: 5
        batch.size: 32768

    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "com.example.kafkaorders"
        spring.json.value.default.type: "com.example.kafkaorders.event.OrderCreatedEvent"
        spring.json.use.type.headers: false
      auto-offset-reset: earliest
      enable-auto-commit: false
      max-poll-records: 20

    listener:
      ack-mode: record

server:
  port: 8080

app:
  kafka:
    topics:
      orders: orders.v1
      orders-retry: orders.v1.retry
      orders-dlt: orders.v1.DLT
